name = "joi-bot"
main = "src/index.ts"
compatibility_date = "2024-12-05"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "joi-db"
database_id = "97385810-ce5f-4b13-9594-ceb07a461041"
