name = "joi-bot"
main = "src/index.ts"
compatibility_date = "2024-12-05"

[triggers]
crons = ["*/5 * * * *"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "0997f17add2045579ebdae1389b6145c"
